### PR TITLE
Globes.co.il ads

### PR DESCRIPTION
**Pull request by AdHelper**
Blocking entire .xyz TLD out from globes.co.il.

### CODE REVIEW

**Comment by EasyListIsrael** [comment]
check this filter
||xyz^$subdocument,domain=globes.co.il

**Comment by AdHelper** [comment]
nope, not working.
http://i.imgur.com/OPkgzr0.jpg

**Comment by AdHelper** [comment]
||*.xyz^$script,domain=globes.co.il will work.

**Comment by AdHelper** [comment]
new domain: [random].website

**Comment by AdHelper** [comment]
added ynet & globes ad server switcher

**Comment by IsraeliAdblocker** [comment]
those were added a while ago.

**Pull request closed without merging**
